services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: bibliotech_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - bibliotech

  nginx:
    image: nginx:1.25-alpine
    container_name: bibliotech_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bibliotech

  db:
    image: mysql:8.0
    container_name: bibliotech_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-bibliotech}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bibliotech

  redis:
    image: redis:7.2-alpine
    container_name: bibliotech_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bibliotech
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

networks:
  bibliotech:
    driver: bridge